#patched crates for rust-1.78
[patch]

[patch.crates-io]
cc = { git = 'https://github.com/helce/cc-rs', branch = 'devel_e2k' }
ctest2 = { git = 'https://github.com/helce/ctest2', branch = 'devel_e2k' }
libc = { git = 'https://github.com/helce/libc', branch = 'devel_e2k' }
libffi = { git = 'https://github.com/helce/libffi-rs', branch = 'devel_e2k' }
libffi-sys = { git = 'https://github.com/helce/libffi-rs', branch = 'devel_e2k' }
linux-raw-sys = { git = 'https://github.com/helce/linux-raw-sys', branch = 'devel_e2k_0.4' }
psm = { git = 'https://github.com/helce/stacker', branch = 'devel_e2k' }
rustix = { git = 'https://github.com/helce/rustix', branch = 'devel_e2k' }
stacker = { git = 'https://github.com/helce/stacker', branch = 'devel_e2k' }
tikv-jemallocator = { path = 'https://github.com/helce/jemallocator', branch = 'devel_e2k' }
tikv-jemallocator-global = { path = 'https://github.com/helce/jemallocator', branch = 'devel_e2k' }
tikv-jemalloc-ctl = { path = 'https://github.com/helce/jemallocator', branch = 'devel_e2k' }
tikv-jemalloc-sys = { path = 'https://github.com/helce/jemallocator', branch = 'devel_e2k' }
#compiletest_rs = { git = 'https://github.com/helce/compiletest-rs' }
#object = { git = 'https://github.com/helce/object' }
