#patched crates for rust-1.78
[patch]

[patch.crates-io]
authenticator = { git = 'https://github.com/helce/authenticator-rs', branch = 'devel_e2k' }
bindgen = { git = 'https://github.com/helce/rust-bindgen', branch = 'devel_e2k' }
caps = { git = 'https://github.com/helce/caps-rs', branch = 'devel_e2k' }
cc = { git = 'https://github.com/helce/cc-rs', branch = 'devel_e2k' }
cfg-expr = { git = 'https://github.com/helce/cfg-expr', branch = 'devel_e2k' }
compiletest_rs = { git = 'https://github.com/helce/compiletest-rs', branch = 'devel_e2k' }
ctest2 = { git = 'https://github.com/helce/ctest2', branch = 'devel_e2k' }
ioctl-sys = { git = 'https://github.com/helce/ioctl', branch = 'devel_e2k' }
libc = { git = 'https://github.com/helce/libc', branch = 'devel_e2k' }
libffi = { git = 'https://github.com/helce/libffi-rs', branch = 'devel_e2k' }
libffi-sys = { git = 'https://github.com/helce/libffi-rs', branch = 'devel_e2k' }
linux-raw-sys_04 = { package = 'linux-raw-sys', git = 'https://github.com/helce/linux-raw-sys', branch = 'devel_e2k_0.4' }
linux-raw-sys_main = { package = 'linux-raw-sys', git = 'https://github.com/helce/linux-raw-sys', branch = 'devel_e2k' }
object = { git = 'https://github.com/helce/object', branch = 'devel_e2k' }
openssl-src_111 = { package = 'openssl-src', git = 'https://github.com/helce/openssl-src-rs', branch = 'devel_e2k_111' }
openssl-src_300 = { package = 'openssl-src', git = 'https://github.com/helce/openssl-src-rs', branch = 'devel_e2k' }
psm = { git = 'https://github.com/helce/stacker', branch = 'devel_e2k' }
ring = { git = 'https://github.com/helce/ring', branch = 'devel_e2k' }
rustix_038 = { package = 'rustix', git = 'https://github.com/helce/rustix', branch = 'devel_e2k_0.38' }
rustix_main = { package = 'rustix', git = 'https://github.com/helce/rustix', branch = 'devel_e2k' }
stacker = { git = 'https://github.com/helce/stacker', branch = 'devel_e2k' }
target-lexicon = { git = 'https://github.com/helce/target-lexicon', branch = 'devel_e2k' }
tikv-jemallocator = { git = 'https://github.com/helce/jemallocator', branch = 'devel_e2k' }
tikv-jemallocator-global = { git = 'https://github.com/helce/jemallocator', branch = 'devel_e2k' }
tikv-jemalloc-ctl = { git = 'https://github.com/helce/jemallocator', branch = 'devel_e2k' }
tikv-jemalloc-sys = { git = 'https://github.com/helce/jemallocator', branch = 'devel_e2k' }
