// patched crates for rust-1.78
[patch]

[patch.crates-io]
libc = { git = 'https://github.com/helce/libc', branch = 'devel_e2k' }
//cc = { git = 'https://github.com/helce/cc-rs' }
ctest2 = { git = 'https://github.com/helce/ctest2', branch = 'devel_e2k' }
//compiletest_rs = { git = 'https://github.com/helce/compiletest-rs' }
//object = { git = 'https://github.com/helce/object' }
//stacker = { git = 'https://github.com/helce/stacker' }
//psm = { git = 'https://github.com/helce/stacker' }
